[ERSSUP-58954]-[FV]-[OAS finalisation of ERSSUP-57567: API Professional user cancels Appointment Request]-[DMW]
NHSDigital/e-referrals-service-api pull request #249
Opened 2022-03-21 15:02 UTC by francisco-videira-nhs

## Summary
* Routine Change

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2022-03-22 12:23 UTC, nhsd-jack-wainwright requested changes
Looks good generally, just a few minor comments 🙂

2022-03-23 08:31 UTC, francisco-videira-nhs commented on sandbox/src/mocks/cancelReferral/responses/ExampleCancelledReferral.json
>          {
I've added more responses and now we have a 1-1 mapping for each example

2022-03-23 08:32 UTC, francisco-videira-nhs commented on specification/e-referrals-service-api.yaml
> +        `effectiveTo` must not be in the past
Changed after discussing with BA

2022-03-23 08:32 UTC, francisco-videira-nhs commented on specification/e-referrals-service-api.yaml
> +        1. I want to cancel the referral and the appointment
Changed after discussing with BA.

2022-03-23 08:33 UTC, francisco-videira-nhs commented on specification/e-referrals-service-api.yaml
> +
Added bullet list.

2022-03-23 08:34 UTC, francisco-videira-nhs commented on specification/e-referrals-service-api.yaml
> +        | Cancelled Referral with Current Deferral                                 | Intend Private With Comment       |
There are now more examples and each request is consistent with response.

2022-03-23 11:43 UTC, francisco-videira-nhs commented on specification/e-referrals-service-api.yaml
> +          * `effectiveFrom` must be in the past, and
For this endpoint, is there something that states that the effectiveFrom should Not be null?

Some refdata entries currently do not have an effectiveFrom date, although these entries aren't retrievable for this endpoint.

2022-03-23 11:46 UTC, francisco-videira-nhs commented on sandbox/src/services/mockResponseProvider.js
> -    else if (ubrn === '000000070001') {
Should add and AND statement to pair the request

2022-03-23 11:57 UTC, francisco-videira-nhs commented on sandbox/src/mocks/cancelReferral/responses/CancelledReferralDeferredIntendPrivateWithComment.json
> +{
Raise with BAs.

2022-03-23 12:06 UTC, francisco-videira-nhs commented on specification/e-referrals-service-api.yaml
> +        e-RS does not allow a referral to be cancelled if there is a current appointment. Therefore, if there is a current appointment associated with the referral, this *must* be cancelled in advanc
Should be re-worded. You can cancel a referral with an appointment.

The overview should state how the user can know what options they have, and also **how they can check if the referral has a current appointment**

2022-03-25 15:53 UTC, francisco-videira-nhs commented on specification/e-referrals-service-api.yaml
> +          * `effectiveFrom` must be in the past, and
BAs decided to leave as is, because it has no functional impact on the endpoint. See https://nhsd-jira.digital.nhs.uk/browse/ERSSUP-58954

2022-03-25 15:54 UTC, francisco-videira-nhs commented on sandbox/src/services/mockResponseProvider.js
> -    else if (ubrn === '000000070001') {
Examples are now powered by matching request to response, and not by UBRN.

2022-03-25 15:55 UTC, francisco-videira-nhs commented on sandbox/src/mocks/cancelReferral/responses/CancelledReferralDeferredIntendPrivateWithComment.json
> +{
This was changed to a scenario "Cancelled referral with existing review outcome", which includes a resolved deferral.

2022-03-25 15:55 UTC, francisco-videira-nhs commented on specification/e-referrals-service-api.yaml
> +        e-RS does not allow a referral to be cancelled if there is a current appointment. Therefore, if there is a current appointment associated with the referral, this *must* be cancelled in advanc
BAs agreed to change this to "e-RS does not allow a referral to be canceled, without also canceling the current appointment."

2022-03-25 15:56 UTC, francisco-videira-nhs commented
This has moved to PR https://github.com/NHSDigital/e-referrals-service-api/pull/254

2022-03-25 15:56 UTC, closed without merging