[ERSSUP-61118]-[]-[Add defining state overview content]-[RG]
NHSDigital/e-referrals-service-api pull request #252
Opened 2022-03-22 16:19 UTC by RajaGovindharaj16

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2022-03-23 15:33 UTC, RajaGovindharaj16 commented
/azp run

2022-03-23 16:05 UTC, RajaGovindharaj16 commented
/azp run

2022-03-23 16:43 UTC, RajaGovindharaj16 commented
/azp run

2022-03-23 17:11 UTC, nhsd-jack-wainwright requested changes
Looks good to me 🙂, just a couple minor comments.

2022-03-24 14:56 UTC, RajaGovindharaj16 commented on specification/e-referrals-service-api.yaml
> +        | `BOOKED`                                                                  | The referral has a current state of booked                                                           |
Raised this question to the business ERSSUP-61167

2025-02-18 09:48 UTC, closed without merging