[ERSSUP-56070]-[]-[Add _ping to CallHeathCheck]-[DMW]
NHSDigital/e-referrals-service-api pull request #68
Opened 2021-09-06 08:06 UTC by nhsd-david-wass

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2021-09-06 14:49 UTC, nhsd-hubert-raich approved these changes

2021-09-10 09:29 UTC, nhsd-hubert-raich approved these changes

2021-09-10 09:30 UTC, nhsd-hubert-raich commented
All good by me, but you will have to rebase and rerun the pipelines as one seem to have failed with intermittent issue.

2021-09-10 10:15 UTC, nhsd-jack-wainwright requested changes
I think there should also be some changes around retrieving the status monitoring API key from the API-M secure variables.

2021-09-10 11:03 UTC, nhsd-jack-wainwright commented on proxies/live/apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml
> +<!-- Get any eRS specific Key Value Map parameters -->
As discussed over slack, given we're not currently using a Key Value Map in Apigee we can probably remove this policy for now.

2021-09-10 11:04 UTC, nhsd-jack-wainwright approved these changes
Looks good to me 🙂

2021-09-15 15:38 UTC, nhsd-david-wass commented
/azp run

2021-09-16 07:30 UTC, nhsd-david-wass commented
/azp run

2021-09-29 09:59 UTC, nhsd-nigel-mellor commented
/azp run

2021-09-29 10:18 UTC, nhsd-hubert-raich approved these changes

2021-09-29 10:42 UTC, nhsd-nigel-mellor commented
/azp run

2021-09-29 10:46 UTC, nhsd-jack-wainwright approved these changes
Looks good to me 🙂

2021-10-01 12:24 UTC, merged